import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ToastContainer, toast } from 'react-toastify';
import { AuthProvider } from "./context/AuthContext";
import { CartProvider } from "./context/AuthContextlength";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fashion website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased w-[100vw] bg-red overflow-x-hidden`}>
        <AuthProvider>
        <CartProvider>
          <ToastContainer />
          <Navbar />
          {children}
          <Footer />
          </CartProvider>
        </AuthProvider>

      </body>

    </html>
  );
}
